### ISSUE TITLE
Compilation of v3.6.0 with OpenFAST v4.1.1

### ISSUE THREAD

**Issue by hamidMech** [Exawind/amr-wind#1689]
## Bug description

Due to the removal of the SuperController from FAST.Farm in OpenFAST v4.1.0, a compilation error occurs when AMR_WIND_ENABLE_OPENFAST=ON. Additionally, enabling HELICS support (AMR_WIND_ENABLE_HELICS=ON) introduces further compilation issues. A function call in /amr-wind/helics.cpp, such as m_vfed->getSubscription(yy), are incompatible with the latest HELICS version (v3.6.1).
 
## Steps to reproduce

1. Compiler used
   - [x] GCC
   - [ ] LLVM
   - [ ] oneapi (Intel)
   - [ ] nvcc (NVIDIA)
   - [ ] rocm (AMD)
   - [x] with MPI
   - [ ] other:
2. Operating system
   - [x] Linux
   - [ ] OSX
   - [ ] Windows
   - [ ] other (do tell ;)):
3. Hardware:
   - [ ] CPU
   - [x] GPU
4. Machine details ():
```
<!-- name, modules loaded, environment variables, etc -->
```
5. Input file attachments():
```
<!-- Please upload the input files in a zip or point to a public branch. --> 
cmake -DAMR_WIND_ENABLE_TESTS=ON -DAMR_WIND_ENABLE_MPI=ON -DAMR_WIND_ENABLE_CUDA=ON -DAMR_WIND_ENABLE_NETCDF=ON -DAMR_WIND_ENABLE_OPENFAST=ON -DAMR_WIND_ENABLE_OPENMP=OFF -DAMR_WIND_ENABLE_HDF5=ON ../
```
6. Error (paste or attach):
```
<!-- error output -->
amr-wind/wind_energy/actuator/turbine/fast/fast_wrapper.H(164): error: identifier "FAST_OpFM_Solution0" is undefined static constexpr auto& FAST_Solution0 = FAST_OpFM_Solution0;
amr-wind/wind_energy/actuator/turbine/fast/fast_wrapper.H(165): error: identifier "FAST_OpFM_Step" is undefined static constexpr auto& FAST_Step = FAST_OpFM_Step;
amr-wind/wind_energy/actuator/turbine/fast/fast_wrapper.H(166): error: identifier "OpFM_InputType" is undefined using OfInputType = OpFM_InputType;
amr-wind/wind_energy/actuator/turbine/fast/fast_wrapper.H(167): error: identifier "OpFM_OutputType" is undefined using OfOutputType = OpFM_OutputType;
amr-wind/wind_energy/actuator/turbine/fast/fast_types.H(98): error: namespace "exw_fast" has no member "SC_DX_InputType" exw_fast::SC_DX_InputType to_sc;
amr-wind/wind_energy/actuator/turbine/fast/fast_types.H(99): error: namespace "exw_fast" has no member "SC_DX_OutputType" exw_fast::SC_DX_OutputType from_sc;

```
7. If this is a segfault, a stack trace from a debug build (paste or attach):
```
<!-- stack trace -->
```

## AMR-Wind information

```
==============================================================================
                AMR-Wind (https://github.com/exawind/amr-wind)

  AMR-Wind version :: v1.4.0-17-g250778a3-DIRTY
  AMR-Wind Git SHA :: 250778a3306e96b46afc117fc722491acaeb6176-DIRTY
  AMReX version    :: 24.03-36-g748f8dfea597

  Exec. time       :: Fri May 10 09:51:15 2024
  Build time       :: May  8 2024 20:36:21
  C++ compiler     :: Clang 17.0.6

  MPI              :: OFF
  GPU              :: OFF
  OpenMP           :: OFF

  No additional third-party libraries enabled

           This software is released under the BSD 3-clause license.
 See https://github.com/Exawind/amr-wind/blob/development/LICENSE for details.
------------------------------------------------------------------------------
```

**Comment by marchdf** [comment]
@hamidMech thanks for opening this. 

I was pretty confident that 3.6.0 builds with openfast 4.1.1. We have dropped 4.0 support because of their change in API. Let me double check on my end again though. 

I haven't tried recently with Helics. It sounds like they updated their API as well? I will see what I can find.

**Comment by marchdf** [comment]
Ok so I am unable to reproduce the build error you get with AW 3.6 and OF 4.1.1. I am using spack to build all this and not raw cmake. 

Re Helics. it looks like we explicitly don't go beyond v3.3.2 according to the spack amr-wind package: https://github.com/spack/spack-packages/blob/develop/repos/spack_repo/builtin/packages/amr_wind/package.py#L271. I guess it's because they changed the API and we dont support those new API changes. I am not familiar with helics but I would be happy to deprecate usage of older helics and update to use a newer helics. Is that typically OK with the community? Or is it like openfast where people like to stick to older versions?

**Comment by rthedin** [comment]
I built AMR-Wind 3.6.0 with OpenFAST 4.1.1 using cmake earlier today with no issues either. Could it be that perhaps it is picking up the wrong openfast installation, since you are not giving its full path with `-DOpenFAST_ROOT`?

**Comment by hamidMech** [comment]
Thank you both for your guidance! Adding "-DAMR_WIND_OPENFAST_VERSION:STRING=4.1.1" fixed the compilation error I mentioned earlier. I also did not run into any issues when compiling with HELICS 3.3.2.
